default_bin = "termbin"

[bins.termbin]
backend = "termbin"
host = "termbin.com:9999"

[bins.pastebin]
backend = "pastebin"
host = "https://pastebin.com/api/api_post.php"

[bins.clbin]
backend = "clbin"
host = "https://clbin.com"

[bins.hastebin]
backend = "hastebin"
host = "https://hastebin.com/"
